apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: rshehi/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
  - image: rshehi/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.js'
        dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}