# apiVersion: skaffold/v2alpha3
# kind: Config
# build:
#   local:
#     push: false
#   artifacts:
#     - image: rshehi/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
      
apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: rshehi/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}